package br.com.oi.sgis.util;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum MessageUtils {
    UNITY_NOT_FOUND_BY_ID("Unidade não encontrada por cód. de barras "),
    UNITY_NOT_FOUND_BY_TERMS("Unidade não encontrada por busca de termos "),
    UNITY_SAVED_SUCCESS("Unidade salva com sucesso, cód. de barras "),
    UNITY_UPDATE_SUCCESS("Aleração realizada com sucesso!"),
    UNITY_UPDATE_ERROR("Erro ao realizar atualização de unidade."),
    UNITY_UPDATE_SAP_ERROR("O item está presente ou com erro no SAP."),
    UNITY_PROP_TRANSF_SUCCESS("O item %s foi transferido com sucesso!"),
    UNITY_PROP_TRANSF_ERROR("Erro ao realizar transferência de propriedade"),
    UNITY_PROP_TRANSF_SAME_DEPART_ERROR("O destino não pode ser igual ao depósito atual."),
    UNITY_PROP_REPO_SUCCESS("O processo de retomada de propriedade do item %s foi realizado com sucesso!"),
    UNITY_PROP_REPO_ERROR("Não foi possível realizar a retomada de propriedade do item %s!"),
    UNITY_UPDT_SIT_SUCCESS("A atualização da situação do item %s foi realizada com sucesso!"),
    UNITY_UPDT_SIT_ERROR("Não foi possível realizar a atualização da situação do item %s!"),
    UNITY_UPDT_SWAP_SUCCESS("SWAP do item solicitado. Aguardar o retorno do processamento do SAP!"),
    UNITY_UPDT_SWAP_ERROR("Não foi possível realizar solicitação do swap do item!"),
    UNITY_PLAN_INSTALLATION_SUCCESS("Instalação de unidade executada com sucesso!"),
    UNITY_PLAN_INSTALLATION_ERROR("Não foi possível concluir a instalação de unidade"),
    UNITY_WRITE_OFF_SUCCESS("Baixa de unidade executada com sucesso!"),
    UNITY_WRITE_OFF_ERROR("Não foi possível concluir a baixa de unidade"),
    UNITY_RECOVER_SUCCESS("Recuperação de item baixado executado com sucesso!"),
    UNITY_RECOVER_ERROR("Não foi possível concluir a recuperação de item baixado"),
    UNITY_REPROCESS_SAP_SUCCESS("Envio do reprocessamento da última operação SAP realizado com sucesso!"),
    UNITY_REPROCESS_SAP_ERROR("Erro durante reprocessamento da última operação SAP."),
    UNITY_RECOVER_INVALID_SITUATION_ERROR("O item está com situação diferente de BXU/BXE/BXO/BXP"),
    UNITY_RECOVER_SAP_STATUS_ERROR("Somente unidades com status de erro no SAP podem ser recuperadas"),
    UNITY_ALREADY_SAVED("Unidade já se encontra cadastrada com cód. barras, "),
    UNITY_SAVED_ERROR("Erro ao salvar unidade"),
    UNITY_INVALID_LOCATION_ERROR("Você não é o depositário deste item.  "),
    UNITY_SWAP_BARCODE_EQ_ORIGINAL_ERROR("Novo Código de barras não pode ser igual ao original."),
    UNITY_SWAP_INVALID_RESPONSIBLE_ERROR("Este item não é da sua área administrativa."),
    UNITY_SWAP_INVALID_SITUATION_ERROR("Swap não permitido para unidades cujas situações não se encontram em DIS ou DEF."),
    UNITY_SWAP_INVALID_NEW_UNITYCODE_ERROR("Novo código da unidade não cadastrado."),
    UNITY_SITUATION_SAME_SIT_ERROR("A situação do item já se encontra "),
    UNITY_SITUATION_NULL_RESERVATION_ERROR("A área reserva não deve ser nula para situação Reserva."),
    UNITY_SITUATION_RESERVATION_ERROR("O item para ser reservado tem que estar disponível."),
    UNITY_SITUATION_INVALID_RESERVATION("Área Administrativa informada para reserva não cadastrada."),
    UNITY_SITUATION_INVALID_SITUATION_ERROR("Nova situação diferente de DIS(disponível)/OFE(oferta)/RES(reserva)/DEF(defeituoso)."),
    UNITY_SITUATION_ONLY_DIS_ALLOWED_ERROR("A situação do item é %s e só pode modificar para DIS."),
    UNITY_WRITE_OFF_PERMISION_ERROR("O usuário %s não tem permissão para realizar baixa na unidade %s"),
    UNITY_WRITE_OFF_ACC_COMP_ERROR("Unidade não tem a marcação da empresa contábil, não pode ser baixada por este motivo!"),
    UNITY_WRITE_OFF_TECH_REPORT_ERROR("Preenchimento do laudo técnico é obrigatório para o motivo selecionado"),
    UNITY_BO_ALREADY_EXISTS_ERROR("O boletim de ocorrência já foi cadastrado com o número %s!"),
    UNITY_BO_REASON_ERROR("O código de barras não é de uma unidade baixada por furto!"),
    UNITY_BO_REGISTER_SUCCESS("Boletim de ocorrência cadastrado com sucesso"),
    INVALID_UNITY_CODE_ERROR("Código de unidade inválido."),
    UNITY_INVALID_SITUATION("Situação inválida para cadastro do item.  "),
    UNITY_INVALID_REQUIRED_SET("Mais de um conjunto de campos obrigatórios foi informado"),
    UNITY_NONE_REQUIRED_SET("Nenhum conjunto de campos obrigatórios foi informado"),
    UNITY_DIFFERENT_AREA_ERROR("Item não está na área administrativa do usuário"),
    AREA_EQUIPAMENT_NOT_FOUND_BY_ID("Modelo unidade não encontrado por Código "),
    AREA_EQUIPAMENT_INVALID("Modelo de unidade informado é inválido."),
    AREA_EQUIPAMENT_NOT_FOUND_BY_MNEMONIC("Modelo unidade não encontrado por Mnemônico "),
    AREA_EQUIPAMENT_INVALID_MNEMONIC("Mnemonico informado não é válido."),
    AREA_EQUIPAMENT_NOT_FOUND_BY_TERMS("Modelo unidade não encontrado por busca de termos "),
    DEPARTMENT_NOT_FOUND_BY_ID("Departamento não encontrado por sigla "),
    CENTRAL_NOT_FOUND_BY_ID("Central não encontrada por código "),
    DEPARTMENT_INVALID("Departamento informado é inválido."),
    DEPARTMENT_RESPONSIBLE_INVALID("Responsável informado é inválido."),
    COMPANY_NOT_FOUND_BY_ID("Empresa não encontrada por sigla "),
    COMPANY_INVALID("Empresa informada é inválida."),
    APPLICATION_NOT_FOUND_BY_ID("Aplicação não encontrada por sigla "),
    APPLICATION_IVALID("Aplicação informada é inválida."),
    EQUIPAMENT_TYPE_NOT_FOUND_BY_ID("Tipo de equipamento não encontrado por código "),
    ELETRIC_PROPERTY_NOT_FOUND_BY_ID("Propriedade elétrica não encontrada por código "),
    EQUIPAMENT_TYPE_INVALID("Tipo de equipamento informado é inválido."),
    MODEL_EQUIPAMENT_TYPE_NOT_FOUND_BY_ID("Modelo de equipamento não encontrado por código "),
    MODEL_EQUIPAMENT_TYPE_INVALID("Modelo de equipamento informado é inválido."),
    SITUATION_NOT_FOUND_BY_ID("Situação não encontrada por Código "),
    SITUATION_CONCILIATE("Situação conciliada com sucesso, código  "),
    SITUATION_CONCILIATE_ERROR("Erro ao conciliar situação."),
    REP_SITUATION_NOT_FOUND_BY_ID("Situação de reparo não encontrada por ID "),
    STATION_NOT_FOUND_BY_ID("Estação não encontrada por ID "),
    MODEL_NOT_FOUND_BY_ID("Portal modelo não encontrado por ID "),
    STATION_INVALID("Estação informada é inválida."),
    FISCAL_DOCUMENT_NOT_FOUND_BY_ID("Documento fiscal não encontrado por ID "),
    ADDRESS_NOT_FOUND_BY_ID("Endereço não encontrado por "),
    BOX_NOT_FOUND_BY_ID("Caixa não encontrada por "),
    BOX_UPDATE_ERROR("Erro ao atualizar caixa "),
    BOX_UPDATE_SUCCESS("Caixa atualizada com sucesso!"),
    TECHNICAL_STAFF_NOT_FOUND_BY_ID("Técnico não encontrado por Código "),
    TECHNICAL_STAFF_INVALID("Técnico informado é inválido."),
    EMPTY_REPORT("Não existem dados para preencher o relatório conforme critérios informados."),
    ERROR_QUERY_REPORT("Ocorreu um erro ao realizar a busca de dados."),
    ERROR_REPORT("Ocorreu um erro na geração do relatório."),
    ERROR_GENERIC_QUERY_REPORT("Ocorreu um erro na criação da consulta genérica."),
    INVALID_PERIOD("A data inicial não deve ser maior que a data final."),
    INVALID_REGISTER_PERIOD("Deve ser informado o período completo (data de cadastro inicial e final)."),
    INVALID_INITIAL_REG_DATE("A data de cadastro inicial não deve ser maior que a final."),
    INVALID_MOVE_PERIOD("Deve ser informado o período completo (data de movimentação inicial e final)."),
    INVALID_INITIAL_MOV_DATE("A data de movimentação inicial não deve ser maior que a final."),
    INVALID_DESTINY_SITUATION("Situação Destino informada é inválida."),
    INVALID_ORIGIN_SITUATION("Situação Origem informada é inválida."),
    INVALID_DESTINY_RESPONSIBLE("Área Destino informada é inválida."),
    INVALID_ORIGIN_RESPONSIBLE("Área Origem informada é inválida."),
    INVALID_DESTINY_TECHNICIAN("Técnico Destino informado é inválido."),
    INVALID_ORIGIN_TECHNICIAN("Técnico Origem informado é inválido."),
    INVALID_BO_NUMBER_ERROR("O número de BO não pode ser nulo para motivos referentes a incidente, incêndio ou furtos."),
    INVALID_SINISTER_NUMBER_ERROR("O número de sinistro não pode ser nulo para motivos referentes a incidentes ou incêndios."),
    UNITY_NOT_REPROCESSABLE_ERROR("Não existe nenhuma última operação SAP para reprocessar!"),
    UNITY_SAP_SUCCESS_ERROR("A última operação SAP deste item é de sucesso, não pode ser reprocessada!"),
    UNITY_ALREADY_REPROCESSABLE_ERROR("A última operação SAP deste item já foi enviada para reprocessamento!"),
    UNITY_SAP_REPROCESS_UNITY_CODE_ERROR("Erro ao recuperar informações para reprocessamento de unidade no SAP."),
    UNITY_INVALID_ITEM_REPAIR_ERROR("Entre com um código de item válido"),
    UNITY_ALREADY_REP_SITUATION_ERROR("Este item já está em reparo!"),
    UNITY_SITUATION_REPAIR_ERROR("O item deve estar com as situacao DIS/EMP/USO/EMU/PRE/DVR/DEF para poder abrir o BR."),
    UNITY_BLANK_FAS_N_REPAIR("O campo 'Nº FAS' não foi preenchido, deseja realmente prosseguir?"),
    UNITY_NOT_EXISTS_FAS_N_REPAIR("O valor do campo 'Nº FAS' está inválido"),
    UNITY_EXISTS_FAS_N_REPAIR("O valor do campo 'Nº FAS' já está cadastrado!"),
    REPAIR_TICKET_FORWARD_SUCCESS("Bilhete de reparo encaminhado com sucesso!"),
    REPAIR_TICKET_FORWARD_ERROR("Erro ao encaminhar bilhete de reparo!"),
    REPAIR_CENTER_NOT_ABLE_ERROR("O departamento informado como centro de reparos não é um centro de reparos. Verifique a tabela de áreas administrativas."),
    REPAIR_TICKET_INVALID_DELIVER_DT("Data de Entrega CSP/CS não pode ser menor que Data fechamento BA/BD."),
    REPAIR_TICKET_INVALID_NORMALIZATION_DT("Data fechamento BA/BD não pode ser maior que a data atual."),
    REPAIR_TICKET_DELIVER_DT_AFTER_NOW("Data de Entrega CSP/CS não pode ser maior que a data atual."),
    REPAIR_TICKET_PERMISION_ERROR("O usuário %s não tem permissão para alterar ou criar o bilhete de reparo"),
    REPAIR_TICKET_PENDENCY_ERROR("Não é possivel gerar pendência quando o depto de origem é igual ao depto devolução."),
    REPAIR_TICKET_SUCCESS("Bilhete de reparo salvo com sucesso, Nº BR "),
    REPAIR_TICKET_ERROR("Erro ao adicionar novo bilhete de reparo"),
    REPAIR_TICKET_SITUATION_UPDT_ERROR("Apenas itens transferidos para reparos ou em reparo podem ser alterados."),
    REPAIR_TICKET_UPDT_ERROR("Este bilhete não é do seu centro de reparos, não foi aberto pelo seu departamento ou seu nível de acesso não é de administrador."),
    REPAIR_TICKET_NOT_FOUND_BY_ID("Bilhete de reparo não encontrado por Nº de BR "),
    REPAIR_TICKET_OPEN_NOT_FOUND_BY_UNITY("Unidade não possui bilhete de reparo com situação ABE - ABERTO "),
    REPAIR_TICKET_UPDATE_SUCCESS("Bilhete de reparo alterado com sucesso, Nº BR "),
    REPAIR_TICKET_ACCEPT_SUCCESS("Aceitação executada com sucesso"),
    REPAIR_TICKET_ACCEPT_ERROR("Ocorreu erro durante o processo de aceitação de BR"),
    UNITY_PROP_ELETRIC_ERROR("Ocorreu erro durante a adição de propriedades elétricas para a unidade. "),
    UNITY_ACCEPT_SUCCESS("Aceitação geral de unidade executada com sucesso"),
    UNITY_ACCEPT_ERROR("Ocorreu erro durante o processo de aceitação geral de unidade"),
    ITEM_NOT_MODEL("O item não é modelo."),
    ITEM_DIFFERENT_DEP("Este item não está na sua lotação."),
    UNITY_COMPOSITION_ERROR("Erro durante a adição do item."),
    UNITY_REMOVE_COMPOSITION_ERROR("Erro durante a remoção do item."),
    UNITY_REMOVE_NO_ITENS_ERROR("Não existem itens para serem removidos."),
    PERIOD_NULL("Período data inicío e fim são obrigatórias."),
    ITEM_INVALID_BARCODE("Item inválido. É um modelo."),
    DEPARTMENT_SAVE_SUCCESS("Registro Incluído com sucesso! Código "),
    DEPARTMENT_SAVE_ERROR("Erro ao inserir nova área adminstrativa."),
    DEPARTMENT_SAVE_ERROR_PARAMETER("Você deve cadastrar as áreas com o prefixo da operadora."),
    DEPARTMENT_SAVE_ERROR_INFOS("Informações não são permitidas para cadastro de centro de reparo."),
    DEPARTMENT_SAVE_ERROR_RESPONSIBLE("Responsável não deve ser informado para departamento com sistema."),
    DEPARTMENT_UPDATE_ERROR("Erro ao alterar departamento."),
    DEPARTMENT_UPDATE_SUCCESS("Registro alterado com sucesso."),
    INVALID_NUMBER("Favor, digite um valor!"),
    INVALID_DATE("Data inválida, informe um período!"),
    ADDRESS_SAVE_SUCCESS("Endereço incluído com sucesso! Código "),
    ADDRESS_SAVE_ERROR("Erro ao inserir novo endereço."),
    ALREADY_EXISTS("Este código já existe"),
    APPLICATION_SAVE_SUCCESS("Aplicação inserida com sucesso. Código "),
    APPLICATION_SAVE_ERROR("Erro ao inserir nova aplicação."),
    APPLICATION_UPDATE_SUCCESS("Aplicação alterada com sucesso. Código "),
    APPLICATION_UPDATE_ERROR("Erro ao alterar aplicação."),
    APPLICATION_DELETE_ERROR("Registro está vinculado a um tipo de equipamento."),
    CENTRAL_SAVE_SUCCESS("Agrupamento de equipamentos inserida com sucesso. Código "),
    CENTRAL_SAVE_ERROR("Erro ao inserir novo agrupamento de equipamentos."),
    CENTRAL_UPDATE_SUCCESS("Agrupamento de equipamentos alterado com sucesso. Código "),
    CENTRAL_UPDATE_ERROR("Erro ao alterar agrupamento de equipamentos."),
    CENTRAL_DELETE_ERROR("Registro está vinculado a uma Unidade ou Bilhete."),
    COMPONENT_NOT_FOUND_BY_ID("Componente não encontrado por código "),
    COMPONENT_TYPE_NOT_FOUND_BY_ID("Tipo de componente não encontrado por código "),
    COMPONENT_SAVE_SUCCESS("Componente inserido com sucesso. Código "),
    COMPONENT_SAVE_ERROR("Erro ao inserir novo componente."),
    COMPONENT_UPDATE_SUCCESS("Componente alterado com sucesso. Código "),
    COMPONENT_UPDATE_ERROR("Erro ao alterar Componente."),
    COMPONENT_DELETE_ERROR("Registro está vinculado a um Departamento "),
    DEFECT_NOT_FOUND_BY_ID("Defeito não encontrado por código "),
    DEFECT_SAVE_SUCCESS("Defeito inserido com sucesso. Código "),
    DEFECT_SAVE_ERROR("Erro ao inserir novo defeito."),
    DEFECT_UPDATE_SUCCESS("Defeito alterado com sucesso. Código "),
    DEFECT_UPDATE_ERROR("Erro ao alterar Defeito."),
    DEFECT_DELETE_ERROR("Registro está vinculado a um Bilhete "),
    DIAGNOSIS_NOT_FOUND_BY_ID("Diagnóstico não encontrado por código "),
    DIAGNOSIS_SAVE_SUCCESS("Diagnóstico inserido com sucesso. Código "),
    DIAGNOSIS_SAVE_ERROR("Erro ao inserir novo diagnóstico."),
    DIAGNOSIS_UPDATE_SUCCESS("Diagnóstico alterado com sucesso. Código "),
    DIAGNOSIS_UPDATE_ERROR("Erro ao alterar Diagnóstico."),
    DIAGNOSIS_DELETE_ERROR("Registro está vinculado a uma Intervenção/Bilhete "),
    CONTRACT_NOT_FOUND_BY_ID("Contrato não encontrado por código "),
    CONTRACT_SAVE_SUCCESS("Contrato inserido com sucesso. Código "),
    CONTRACT_SAVE_ERROR("Erro ao inserir novo contrato."),
    CONTRACT_UPDATE_SUCCESS("Contrato alterado com sucesso. Código "),
    CONTRACT_UPDATE_ERROR("Erro ao alterar Contrato."),
    CONTRACT_DELETE_ERROR("O Contrato possui vínculos com Contratos de Modelo de Unidades."),
    MODEL_CONTRACT_SAVE_ERROR("Erro ao incluir modelo para Contrato."),
    DOLLAR_ALREADY_REGISTERED("Já existe cotação cadastrada para essa data! "),
    DOLLAR_NOT_FOUND_BY_ID("Dólar não encontrado por data "),
    DOLLAR_SAVE_SUCCESS("Dólar inserido com sucesso. Data "),
    DOLLAR_SAVE_ERROR("Erro ao inserir novo dólar."),
    DOLLAR_UPDATE_SUCCESS("Dólar alterado com sucesso. Data "),
    DOLLAR_UPDATE_ERROR("Erro ao alterar Dólar."),
    DOLLAR_DELETE_ERROR("Erro ao deletar Dólar "),
    DOCUMENT_ALREADY_REGISTERED("Documento Fiscal já cadastrado! "),
    DOCUMENT_NOT_FOUND_BY_ID("Documento fiscal não encontrado "),
    DOCUMENT_SAVE_SUCCESS("Documento fiscal inserido com sucesso.  "),
    DOCUMENT_SAVE_ERROR("Erro ao inserir novo documento."),
    DOCUMENT_UPDATE_SUCCESS("Documento fiscal alterado com sucesso. "),
    DOCUMENT_UPDATE_ERROR("Erro ao alterar Documento fiscal."),
    DOCUMENT_DELETE_ERROR("Erro ao deletar Documento fiscal "),
    STATION_ALREADY_REGISTERED("Estação já existente! "),
    STATION_SAVE_SUCCESS("Estação inserida com sucesso.  "),
    STATION_SAVE_ERROR("Erro ao inserir nova estação."),
    STATION_UPDATE_SUCCESS("Estação alterada com sucesso. "),
    STATION_UPDATE_ERROR("Erro ao alterar Estação."),
    STATION_DELETE_ERROR("Registro está vinculado a um Bilhete ou a uma Unidade!"),
    UF_NOT_FOUND_BY_ID("UF não encontrada."),
    MANUFACTURER_NOT_FOUND_BY_ID("Fabricante não encontrado "),
    MANUFACTURER_SAVE_SUCCESS("Fabricante inserido com sucesso. Código "),
    MANUFACTURER_SAVE_ERROR("Erro ao inserir novo fabricante."),
    MANUFACTURER_UPDATE_SUCCESS("Fabricante alterado com sucesso. Código "),
    MANUFACTURER_UPDATE_ERROR("Erro ao alterar Fabricante."),
    MANUFACTURER_DELETE_ERROR("Erro ao deletar Fabricante "),
    COMPANY_SAVE_SUCCESS("Empresa inserida com sucesso. Código "),
    COMPANY_SAVE_ERROR("Erro ao inserir nova empresa."),
    COMPANY_UPDATE_SUCCESS("Empresa alterada com sucesso. Código "),
    COMPANY_UPDATE_ERROR("Erro ao alterar Empresa."),
    COMPANY_ADDRESS_ERROR("Você deve cadastrar ao menos um endereço para empresa. "),
    COMPANY_MANUFACTURER_ERROR("O cadastro de novo fabricante só é possível através do PORTAL. "),
    COMPANY_CNPJ_REGISTERER_ERROR("O CNPJ já está cadastrado em outra empresa. "),
    COMPANY_PROVIDER_OR_HOLDING_ERROR("Não pode ser cadastrado cliente como operador e prestador. "),
    INTERVENTION_NOT_FOUND_BY_ID("Intervenção não encontrada por código "),
    INTERVENTION_SAVE_SUCCESS("Intervenção inserida com sucesso. Código "),
    INTERVENTION_SAVE_ERROR("Erro ao inserir nova intervenção."),
    INTERVENTION_UPDATE_SUCCESS("Intervenção alterada com sucesso. Código "),
    INTERVENTION_UPDATE_ERROR("Erro ao alterar Intervenção."),
    INTERVENTION_DELETE_ERROR("Registro está vinculado a uma INTERVENÇÃO DO BILHETE DE REPAROS! "),
    DEP_UNITY_ALREADY_REGISTERED("Já existe cadastro para área administrativa e modelo de placa!! "),
    DEP_UNITY_NOT_FOUND_BY_ID("Localização de armazenagem não encontrada "),
    DEP_UNITY_SAVE_SUCCESS("Localização de armazenagem inserida com sucesso.  "),
    DEP_UNITY_SAVE_ERROR("Erro ao inserir nova Localização de armazenagem."),
    DEP_UNITY_UPDATE_SUCCESS("Localização de armazenagem alterada com sucesso. "),
    DEP_UNITY_UPDATE_LOC_SUCCESS("Localização de armazenagem de unidades DISPONÍVEIS alterada com sucesso. "),
    DEP_UNITY_UPDATE_LOC_ERROR("Erro ao alterar Localização de armazenagem de unidades DISPONÍVEIS. "),
    DEP_UNITY_UPDATE_ERROR("Erro ao alterar Localização de armazenagem."),
    DEP_UNITY_DELETE_ERROR("Erro ao deletar Localização de armazenagem "),
    DEP_UNITY_DIFFERENT_USER_DEP("Este modelo não é do seu departamento!"),
    TECHNOLOGY_ALREADY_EXISTS("Tecnologia já cadastrada. "),
    TECHNOLOGY_NOT_FOUND_BY_ID("Tecnologia não encontrada por código "),
    TECHNOLOGY_SAVE_SUCCESS("Tecnologia inserida com sucesso. Código "),
    TECHNOLOGY_SAVE_ERROR("Erro ao inserir nova Tecnologia."),
    TECHNOLOGY_UPDATE_SUCCESS("Tecnologia alterada com sucesso. Código "),
    TECHNOLOGY_UPDATE_ERROR("Erro ao alterar Tecnologia."),
    TECHNOLOGY_DELETE_ERROR("Tecnologia vinculada a um modelo equipamento! "),
    MODEL_EQUIPAMENT_TYPE_SAVE_SUCCESS("Modelo Equipamento inserido com sucesso. Código "),
    MODEL_EQUIPAMENT_TYPE_SAVE_ERROR("Erro ao inserir novo Modelo Equipamento."),
    MODEL_EQUIPAMENT_TYPE_UPDATE_SUCCESS("Modelo Equipamento alterado com sucesso. Código "),
    MODEL_EQUIPAMENT_TYPE_DESC_SUCCESS("Flag descontinuada de equipamento alterada com sucesso. "),
    MODEL_EQUIPAMENT_TYPE_DESC_ERROR("Erro ao atualizar equipamento com flag descontinuada."),
    MODEL_EQUIPAMENT_TYPE_UPDATE_ERROR("Erro ao alterar Modelo Equipamento."),
    MODEL_EQUIPAMENT_TYPE_DELETE_ERROR("O Modelo de Equipamento possui vínculo com Modelo de  Unidades. "),
    AREA_EQUIPAMENT_DELETE_ERROR("O Modelo de Unidade possui vínculo com Unidade! "),
    EQUIP_PROP_ELETRIC_ERROR("Ocorreu erro durante a adição de propriedades elétricas para a equipamento. "),
    AREA_EQUIPAMENT_SAVE_SUCCESS("Equipamento inserido com sucesso. Código "),
    AREA_EQUIPAMENT_SAVE_ERROR("Erro ao inserir novo Equipamento."),
    AREA_EQUIPAMENT_UPDATE_SUCCESS("Equipamento alterado com sucesso. Código "),
    AREA_EQUIPAMENT_UPDATE_ERROR("Erro ao alterar Equipamento."),
    ELETRIC_PROPERTY_ALREADY_EXISTS("Prop. Elétrica já cadastrada. "),
    ELETRIC_PROPERTY_SAVE_SUCCESS("Prop. Elétrica inserida com sucesso. Código "),
    ELETRIC_PROPERTY_SAVE_ERROR("Erro ao inserir nova Prop. Elétrica."),
    ELETRIC_PROPERTY_UPDATE_SUCCESS("Prop. Elétrica alterada com sucesso. Código "),
    ELETRIC_PROPERTY_UPDATE_ERROR("Erro ao alterar Prop. Elétrica."),
    ELETRIC_PROPERTY_DELETE_ERROR("Prop. Elétrica possui vínculos com Equipamento ou Unidades! "),
    MEASUREMENT_ALREADY_EXISTS("Já existe cadastro para essa Unidade de Medida! "),
    MEASUREMENT_NOT_FOUND_BY_ID("Unidade de medida não encontrada por código "),
    MEASUREMENT_SAVE_SUCCESS("Unidade de medida inserida com sucesso. Código "),
    MEASUREMENT_SAVE_ERROR("Erro ao inserir nova Unidade de medida."),
    MEASUREMENT_UPDATE_SUCCESS("Unidade de medida alterada com sucesso. Código "),
    MEASUREMENT_UPDATE_ERROR("Erro ao alterar Unidade de medida."),
    MEASUREMENT_DELETE_ERROR("Unidade de Medida está vinculado a uma Propriedade Elétrica! "),
    COMPANY_MODEL_ALREADY_EXISTS("Empresa/Modelo já cadastrado! "),
    COMPANY_MODEL_NOT_FOUND_BY_ID("Empresa/Modelo não encontrada por código "),
    COMPANY_MODEL_SAVE_SUCCESS("Empresa/Modelo inserida com sucesso.  "),
    COMPANY_MODEL_SAVE_ERROR("Erro ao inserir nova Empresa/Modelo."),
    COMPANY_MODEL_UPDATE_SUCCESS("Empresa/Modelo alterada com sucesso.  "),
    COMPANY_MODEL_UPDATE_ERROR("Erro ao alterar Empresa/Modelo."),
    COMPANY_MODEL_DELETE_ERROR("Erro ao excluir Empresa/Modelo. "),
    TECHNIQUE_ALREADY_EXISTS("Técnica já cadastrada. "),
    TECHNIQUE_NOT_FOUND_BY_ID("Técnica não encontrada por código "),
    TECHNIQUE_SAVE_SUCCESS("Técnica inserida com sucesso. Código "),
    TECHNIQUE_SAVE_ERROR("Erro ao inserir novo Técnica."),
    TECHNIQUE_UPDATE_SUCCESS("Técnica alterada com sucesso. Código "),
    TECHNIQUE_UPDATE_ERROR("Erro ao alterar Técnico."),
    TECHNIQUE_DELETE_ERROR("Registro vinculado a um Modelo de Equipamento! "),
    BOX_TYPE_ALREADY_EXISTS("Já possui cadastro para esse Tipo de Caixa!"),
    BOX_TYPE_NOT_FOUND_BY_ID("Tipo de Caixa não encontrado por código "),
    BOX_TYPE_SAVE_SUCCESS("Tipo de Caixa inserido com sucesso. Código "),
    BOX_TYPE_SAVE_ERROR("Erro ao inserir novo Tipo de Caixa."),
    BOX_TYPE_UPDATE_SUCCESS("Tipo de Caixa alterado com sucesso. Código "),
    BOX_TYPE_UPDATE_ERROR("Erro ao alterar Tipo de Caixa."),
    BOX_TYPE_DELETE_ERROR("Tipo de Caixa está vinculado a uma caixa!"),
    COMPONENT_TYPE_ALREADY_EXISTS("Já possui cadastro para esse Tipo de Componente!"),
    COMPONENT_TYPE_SAVE_SUCCESS("Tipo de Componente inserido com sucesso. Código "),
    COMPONENT_TYPE_SAVE_ERROR("Erro ao inserir nova Tipo de Componente."),
    COMPONENT_TYPE_UPDATE_SUCCESS("Tipo de Componente alterado com sucesso. Código "),
    COMPONENT_TYPE_UPDATE_ERROR("Erro ao alterar Tipo de Componente."),
    COMPONENT_TYPE_DELETE_ERROR("Tipo de Componente está vinculado a um Componente!"),
    COMPONENT_MOV_TYPE_ALREADY_EXISTS("Já possui cadastro para esse Tipo de Movimentação de Componente!"),
    COMPONENT_MOV_TYPE_NOT_FOUND_BY_ID("Tipo de Mov. de Componente não encontrado por código "),
    COMPONENT_MOV_TYPE_SAVE_SUCCESS("Tipo de Mov. de Componente inserido com sucesso. Código "),
    COMPONENT_MOV_TYPE_SAVE_ERROR("Erro ao inserir novo Tipo de Mov. de Componente."),
    COMPONENT_MOV_TYPE_UPDATE_SUCCESS("Tipo de Mov. de Componente alterado com sucesso. Código "),
    COMPONENT_MOV_TYPE_UPDATE_ERROR("Erro ao alterar Tipo de Mov. de Componente."),
    COMPONENT_MOV_TYPE_DELETE_ERROR("Tipo de Mov. de Componente está vinculado a uma movimentação de unidade!"),
    TIME_ALREADY_EXISTS("Já possui cadastro do equipamento para a intervenção!"),
    TIME_NOT_FOUND_BY_ID("Tempo Padrão não encontrado por código "),
    TIME_SAVE_SUCCESS("Tempo Padrão inserido com sucesso.  "),
    TIME_SAVE_ERROR("Erro ao inserir novo Tempo Padrão."),
    TIME_UPDATE_SUCCESS("Tempo Padrão alterado com sucesso. "),
    TIME_UPDATE_ERROR("Erro ao alterar Tempo Padrão."),
    TIME_DELETE_ERROR("Tempo Padrão está vinculado a uma movimentação de unidade!"),
    EQUIPMENT_TYPE_ALREADY_EXISTS("Já possui cadastro para esse Tipo de Equipamento!"),
    EQUIPMENT_TYPE_SAVE_SUCCESS("Tipo de Equipamento inserido com sucesso. Código "),
    EQUIPMENT_TYPE_SAVE_ERROR("Erro ao inserir novo Tipo de Equipamento."),
    EQUIPMENT_TYPE_UPDATE_SUCCESS("Tipo de Equipamento alterado com sucesso. Código "),
    EQUIPMENT_TYPE_UPDATE_ERROR("Erro ao alterar Tipo de Equipamento."),
    EQUIPMENT_TYPE_DELETE_ERROR("Tipo de Equipamento está vinculado a um Modelo de equipamento!"),
    PARAMETER_ALREADY_EXISTS("Já possui cadastro para esse Parâmetro!"),
    PARAMETER_NOT_FOUND_BY_ID("Parâmetro não encontrado por código "),
    PARAMETER_PREFIX_NOT_NUMERIC("Prefixo deve ser numérico."),
    PARAMETER_SAVE_SUCCESS("Parâmetro inserido com sucesso.  Código "),
    PARAMETER_SAVE_ERROR("Erro ao inserir novo Parâmetro."),
    PARAMETER_UPDATE_SUCCESS("Parâmetro alterado com sucesso. Código "),
    PARAMETER_UPDATE_ERROR("Erro ao alterar Parâmetro."),
    PARAMETER_DELETE_ERROR("Erro ao deletar Parâmetro."),
    TECHNICAL_STAFF_ALREADY_EXISTS("Matrícula já cadastrada!"),
    TECHNICAL_STAFF_SAVE_SUCCESS("Técnico inserido com sucesso.  Código "),
    TECHNICAL_STAFF_SAVE_ERROR("Erro ao inserir novo Técnico."),
    TECHNICAL_STAFF_SAVE_ERROR_ADMIN("Você não possui permissão para inativar o técnico."),
    TECHNICAL_STAFF_UPDATE_SUCCESS("Técnico alterado com sucesso. Código "),
    TECHNICAL_STAFF_UPDATE_ERROR("Erro ao alterar Técnico."),
    TECHNICAL_STAFF_UPDATE_MH_SUCCESS("Valor homem/hora atualizado com sucesso. Código "),
    TECHNICAL_STAFF_UPDATE_MH_ERROR("Erro ao alterar valor homem/hora."),
    TECHNICAL_STAFF_DELETE_ERROR("Erro ao deletar Técnico."),
    MODEL_TS_ALREADY_EXISTS("Já possui cadastro para esse Modelo por Técnico!"),
    MODEL_TS_NOT_FOUND_BY_ID("Modelo por Técnico não encontrado. "),
    MODEL_TS_SAVE_SUCCESS("Modelo por Técnico inserido com sucesso.  "),
    MODEL_TS_SAVE_ERROR("Erro ao inserir novo Modelo por Técnico."),
    MODEL_TS_UPDATE_SUCCESS("Modelo por Técnico alterado com sucesso."),
    MODEL_TS_UPDATE_ERROR("Erro ao alterar Modelo por Técnico."),
    MODEL_TS_DELETE_ERROR("Erro ao deletar Modelo por Técnico."),
    CLOSE_REPAIR_SUCCESS("Fechamento executado com sucesso!"),
    CLOSE_REPAIR_ERROR("Erro ao fechar bilhete de reparo."),
    INVALID_CLOSE_SITUATION("Situação de bilhete inválida para fechamento!."),
    INVALID_FORWARD_TICKET("Esta unidade tem uma intervenção aberta. Feche a intervenção antes de reencaminhar"),
    DEVOLUTION_REPAIR_SUCCESS("Devolução executada com sucesso!"),
    DEVOLUTION_REPAIR_ERROR("Erro ao executar devolução de bilhete de reparo."),
    CANCEL_REPAIR_SUCCESS("Cancelamento executado com sucesso!"),
    CANCEL_REPAIR_ERROR("Erro ao executar cancelamento de bilhete de reparo."),
    TRANSFER_TECHNICIAN_SUCCESS("Transferência para técnico executada com sucesso!"),
    TRANSFER_TECHNICIAN_ERROR("Erro ao executar transferência para técnico."),
    TRANSFER_PROVIDER_SUCCESS("Transferência executada com sucesso!"),
    TRANSFER_PROVIDER_ERROR("Erro ao executar transferência para prestador."),
    INSTA_CLIENT_PROVIDER_SUCCESS("Instalação executada com sucesso!"),
    INSTA_CLIENT_PROVIDER_ERROR("Erro ao executar instalação pelo prestador."),
    INSTA_CLIENT_PROVIDER_ADDRESS_ERROR("Endereço informado não pertence a cliente selecionado."),
    INSTA_CLIENT_TECHNICIAN_SUCCESS("Instalação executada com sucesso!"),
    INSTA_CLIENT_TECHNICIAN_ERROR("Erro ao executar transferência pelo técnico."),
    CABLE_MOV_NOT_FOUND_BY_ID("Movimento de cabos não encontrado. "),
    CABLE_MOV_SAVE_SUCCESS("Movimento de cabos inserido com sucesso.  "),
    CABLE_MOV_SAVE_ERROR("Erro ao inserir novo Movimento de cabos."),
    CABLE_MOV_PROP_ERROR("Não existe propriedades elétricas para a unidade selecionada!"),
    LABEL_HOLDING_ERROR("Você não pode gerar etiquetas que não sejam da sua operadora"),
    LABEL_SIZE_ERROR("Entre com um código de barras válido!"),
    BARCODE_ALREADY_EXISTS("Código de barras já utilizado por outra unidade."),
    CHANGE_BARCODE_SUCCESS("Troca de etiqueta executada com sucesso!"),
    CHANGE_BARCODE_ERROR("Erro ao executar troca de etiqueta."),
    EMPTY_BOX("A caixa selecionada não possui itens!"),
    REPAIR_TICKET_DESIG_TECH_SUCCESS("Substituição executada com sucesso."),
    REPAIR_TICKET_DESIG_TECH_ERROR("Erro na Substituição do Técnico!"),
    TICKET_INTERV_NOT_FOUND_BY_ID("Intervenção de bilhete não encontrada para bilhete "),
    TICKET_INTERV_SAVE_SUCCESS("Intervenção de bilhete inserida com sucesso.  "),
    TICKET_INTERV_SAVE_ERROR("Erro ao inserir intervenção de bilhete."),
    TICKET_INTERV_ALREADY_EXISTS("Já existe intervenção para o bilhete com o mesmo código de barras"),
    TICKET_INTERV_SAVE_TRIAGE_ERROR("Este item deve ser triado."),
    TICKET_INTERV_EXT_SAVE_TRIAGE_ERROR("Este item deve ser triado antes de executar o reparo externo."),
    TICKET_INTERV_EXT_MANTAINER_NULL_ERROR("Este item está sem o mantenedor externo designado."),
    TICKET_INTERV_EXT_MANTAINER_ERROR("Este item foi designado um mantenedor diferente do especificado na solicitação de orçamento"),
    TICKET_INTERV_SAVE_FORWARDING_ERROR("Este item não está encaminhado para reparo interno."),
    TICKET_INTERV_SAVE_TECHNICIAN_ERROR("Este item não tem técnico designado."),
    TICKET_INTERV_UNITY_SIT_ERROR("Unidade selecionada não está em reparo!"),
    TICKET_INTERV_SITUATION_ERROR("Este item ainda não foi aceito. Item com situação ABE."),
    TICKET_INTERV_CR_ERROR("Este item não é do seu centro de reparos."),
    TICKET_DIAGNOSIS_SAVE_ERROR("Erro ao incluir diagnóstico para Intervenção de Bilhete."),
    TICKET_COMPONENT_SAVE_ERROR("Erro ao incluir componente para Intervenção de Bilhete."),
    TICKET_INTERV_UPDATE_SUCCESS("Intervenção de bilhete alterada com sucesso."),
    TICKET_INTERV_UPDATE_ERROR("Erro ao alterar intervenção de bilhete."),
    TICKET_INTERV_UPDATE_FORWARD_ERROR("Erro ao realizar encaminhamento."),
    TICKET_INTERV_CLOSE_SUCCESS("Intervenção de bilhete fechada com sucesso."),
    TICKET_INTERV_CLOSE_ERROR("Erro ao realizar fechamento de intervenção de bilhete."),
    ESTIMATE_NOT_FOUND_BY_ID("Orçamento não encontrada por código "),
    ESTIMATE_SAVE_SUCCESS("Orçamento inserido com sucesso. Código "),
    ESTIMATE_SAVE_ERROR("Erro ao inserir novo orçamento."),
    ESTIMATE_UPDATE_SUCCESS("Orçamento alterado com sucesso. Código "),
    ESTIMATE_UPDATE_ERROR("Erro ao alterar orçamento."),
    ESTIMATE_REPAIR_CENTER_ERROR("Centro de reparos não corresponde a lotação do usuário logado!"),
    ESTIMATE_EXTERNAL_REP_SEND_ERROR("Orçamento já enviado para reparo externo! Não pode ser alterado!"),
    TICKET_INTERV_SITUATION_EXT_ERROR("Este item não foi encaminhado para reparo externo."),
    ESTIMATE_EXTERNAL_REP_SEND_OUT_ERROR("Este orçamento já foi enviado."),
    ESTIMATE_EXTERNAL_REP_DEPARTMENT_ERROR("Este orçamento não pertence a sua Área Administrativa."),
    ESTIMATE_EXTERNAL_REP_DATE_NF_ERROR("Data da Nota fiscal não pode ser maior que a data atual."),
    ESTIMATE_EXTERNAL_OUTPUT_ERROR("Erro ao realizar envio para Reparo Externo."),
    ESTIMATE_EXTERNAL_OUTPUT_SUCCESS("Envio para Reparo Externo executado com sucesso!"),
    ESTIMATE_NOT_SENT_ERROR("Este orçamento ainda não foi enviado."),
    ESTIMATE_SENT_DEPARTMENT_ERROR("Este orçamento não é do seu centro de reparos."),
    ITEM_ESTIMATE_NOT_FOUND_BY_ID("Orçamento do item não encontrado por código. "),
    ITEM_ESTIMATE_ANALYSIS_UPDATE_SUCCESS("Análise de itens realizada com sucesso. Código "),
    ITEM_ESTIMATE_ANALYSIS_UPDATE_ERROR("Erro realizar análise de itens de orçamento."),
    ITEM_ESTIMATE_APPROVE_ERROR("Erro ao aprovar item de orçamento. "),
    ITEM_ESTIMATE_CANCEL_ERROR("Erro ao cancelar item de orçamento."),
    ITEM_ESTIMATE_APPROVE_CANCEL_SUCCESS("Aprovação/Cancelamento de itens de orçamento realizada com sucesso! "),
    ITEM_ESTIMATE_CANCEL_CANCEL_ERROR("Erro na execução da aprovação/cancelamento."),
    ESTIMATE_CANCEL_ERROR("Erro na execução do cancelamento."),
    ESTIMATE_CANCEL_SUCCESS("Cancelamento de orçamento executado com sucesso!"),
    EXTERNAL_REPAIR_RETURN_ERROR("Erro ao retornar reparo externo."),
    EXTERNAL_REPAIR_RETURN_SUCCESS("Retorno de reparo externo executado com sucesso!"),
    EXTERNAL_REPAIR_RETURN_ARRIVAL_ERROR("A data de chegada não deve ser superior que a data atual."),
    EXTERNAL_REPAIR_RETURN_NF_DATE_ERROR("A data de chegada não deve ser inferior que a da nota fiscal."),
    EXTERNAL_REPAIR_RETURN_SUBSTITUTION_ERROR("Deve ser informado um novo código de barras para substituição"),
    GENERIC_QUERY_NOT_FOUND_BY_ID("Consulta não encontrada por código "),
    GENERIC_QUERY_CREATE_SUCCESS("Consulta criada com sucesso. Código "),
    GENERIC_QUERY_UPDATE_SUCCESS("Consulta atualizada com sucesso. Código "),
    GENERIC_QUERY_CREATE_ERROR("Erro ao criar nova consulta."),
    GENERIC_QUERY_UPDATE_DIFFERENT_USER_ERROR("A consulta só pode ser alterada pelo usuário que criou."),
    GENERIC_QUERY_DELETE_DIFFERENT_USER_ERROR("Só é permitido a exclusão da consulta pelo usuário que criou."),
    GENERIC_QUERY_UPDATE_ERROR("Erro ao atualizar consulta."),
    GENERIC_QUERY_DELETE_ERROR("Erro ao deletar consulta."),
    GENERIC_QUERY_ITEM_SAVE_ERROR("Erro ao salvar consulta item."),
    GENERIC_QUERY_ITEM_DELETE_ERROR("Erro ao deletar consulta item."),

    ;
    private final  String description;
}
